### ISSUE TITLE
Checkpoints

### ISSUE THREAD

**Issue by 1980x** [katerynaCh/MMA-DFER#1]
Hi,

Awesome work.

When do you plan to release the trained model weights?

Thanks

**Comment by katerynaCh** [comment]
Hi! I have uploaded the models trained on DFEW and added an evaluation script. Please refer to the Readme.

**Comment by OdingdongO** [comment]
Will the model trained on the MAFW dataset be released？

**Comment by katerynaCh** [comment]
@OdingdongO Hi, I have released the MAFW models. Please refer to the README
